config/routes.rb
CampusHunter::Application.routes.draw do

  root :to => "applicant#home"
  resources :user

  get "session/destroy"
  get "session/new"
  post "session/new"
  get "log_in" => "session#new", :as => "log_in"
  get "log_out" => "session#destroy", :as => "log_out"
  get "sign_up" => "user#new", :as => "sign_up"
  get "delete_user" => "user#destroy", :as => "delete_user"
  post "user/del"
  post "applicant/create"

  resources :college do
    collection do
      get "show"
    end
  end

  resources :applicant do
    collection do
    get "home"
    get "upload"
    post "upload"
    post "create"
    get "create"
    end
  end

end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
  attr_accessible :collegeId
end

app/models/applicant_data.rb
class ApplicantData < ActiveRecord::Base
  attr_accessible :college_header_id, :applicant_id, :value
  belongs_to :college_header
  belongs_to :applicant
end

app/models/college.rb
class College < ActiveRecord::Base
  attr_accessible :created_by, :name, :updated_by
end

app/models/college_header.rb
class CollegeHeader < ActiveRecord::Base
  attr_accessible :college_id, :created_by, :header_id, :updated_by
  has_many :college, :foreign_key => "college_id"
  has_many :header, :foreign_key => "header_id"

end

app/models/header.rb
class Header < ActiveRecord::Base
  attr_accessible :created_by, :name, :updated_by
end

app/models/round.rb
class Round < ActiveRecord::Base
  attr_accessible :created_by, :name, :updated_by
end

app/models/round_applicant_data.rb
class RoundApplicantData < ActiveRecord::Base
  belongs_to :applicants
  belongs_to :round
  attr_accessible :comment, :interviewee, :status
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :created_by, :password, :password_salt, :role, :updated_by, :username, :password_confirmation

  before_save :encrypt_password

  def self.authenticate(username, password)
    user = find_by_username(username)
    if user && user.password == BCrypt::Engine.hash_secret(password, user.password_salt)
      return user
    else
      nil
    end
  end

  validates :username, :password, :presence => true
  validates :password, :confirmation => {:message => "you entered do not match"}
  validates :username, :uniqueness => true
  validates :password, :length => {:in => 4..20}

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password = BCrypt::Engine.hash_secret(password, password_salt)
  end
end

app/controllers/applicant_controller.rb
#require 'csv'
class ApplicantController < ApplicationController

  #before_filter :require_login
  include ApplicantHelper
  def home
  end

  def upload

  end

  def create
  if(College.find_by_name(params[:college_name]).nil?)
  college = College.new(:name => params[:college_name])
  college.save
  upload_csv params[:file_name],college
  college.update_attribute(:number_of_applicants, Applicant.where(:college_id => college.id).count)
    render "home"
  else
    @message = "College name has already been taken"
    render "upload"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #helper_method :current_user
  #
  #
  #def current_user
  #  @current_user ||= User.find(session[:user_id]) if session[:user_id]
  #end
  #
  #def require_login
  #  if session[:user_id] == nil
  #    flash[:error] = "You must be logged in to access this page"
  #    redirect_to :log_in
  #  end
  #end

end

app/controllers/college_controller.rb
class CollegeController < ApplicationController
  def show
    @colleges = College.all
    respond_to do |format|
          format.html { render 'college/show' }
      end
    #@colleges = []
    #if !params[:name].nil?
    #  @colleges = Kaminari.paginate_array(College.find_all_by_poolName(params[:name])).page(params[:page]).per(100)
    #else
    #  colleges = College.all
    #  colleges.each do |college|
    #    if(college.poolName.nil?)
    #      @colleges << college
    #    end
    #  end
    #  @colleges = Kaminari.paginate_array(@colleges).page(params[:page]).per(100)
    #  respond_to do |format|
    #    format.html { render 'college/show' }
    #    format.json { render json: @colleges }
    #  end
    #end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    @message = "WELCOME"
  end

  def create
    user = User.authenticate(params[:username], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_path
    else
      #require "pry"
      #binding.pry
      @message = "Invalid email or password"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/session/new", :notice => "Successfully logged out!"
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  #before_filter :require_login
  layout "session"

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      @message = "User Added Successfully!"
    end
    render "new"
  end

  def del
    @user = User.find_by_username(params[:username])
    if @user.nil?

      @message = "User doesn't exist!"
    elsif @user.destroy
      @message = "User deleted successfully!"
    end
    render :action => "destroy"
  end

  def destroy
  end

end

app/helpers/applicant_helper.rb
require "csv"
module ApplicantHelper
  private
  def upload_csv(file_name, college)
col = college
file = file_name
    header_row = CSV.new(file.tempfile, :headers => false).first
      header_row.each do |header|
        if Header.find_by_name(header).nil?
          Header.create!(:name => header)
        end
        header_id = Header.find_by_name(header).id
        CollegeHeader.create!(:college_id => college.id, :header_id => header_id)
      end
      CSV.new(file_name.tempfile, :headers => true).each do |row|
        app = Applicant.new()
        app.save
        app.update_attribute(:college_id, college.id)
        hash = row.to_hash
        (hash.keys()).each do |key|
          header = Header.find_by_name(key)
          if header.nil?
            header = Header.create!(:name => key)
          end
          college_header = CollegeHeader.where(:college_id => college.id, :header_id => header.id).first
          if(college_header.nil?)
          college_header = CollegeHeader.create!(:college_id => college.id, :header_id => header.id)
          end
          ApplicantData.create!(:college_header_id => college_header.id, :applicant_id => app.id, :value => hash[key])
        end
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/college_helper.rb
module CollegeHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/applicant/home.html.erb
<% content_for :title do %>
    CampusHunter
<% end %>

<h1>HOME PAGE</h1>
<% content_for :styles do %>
    <%= stylesheet_link_tag "pro_dropline_ie" %>
    <%= stylesheet_link_tag "pro_dropline" %>
<% end %>

<div id="page-heading">

  <div style="float: left;">
    <br/>
    <h1>
      <%= link_to "List of Colleges", "/college/show", :id => "collegeList", :style => "color: #4b4b4b;" %>
    </h1>
    <br/>
    <h1>
      <%= link_to "List of Pools", "/pool/show", :id => "poolList", :style => "color: #4b4b4b;" %>
    </h1>
    <br/><h1>
    <%= link_to "Add College", "/applicant/upload", :id => "poolList", :style => "color: #4b4b4b;" %>
  </h1><br/>
  </div>
</div>

app/views/applicant/upload.html.erb
<% content_for :title do %>
    CampusHunter - Add New College
<% end %>

<% content_for :scripts do %>

    <script type="text/javascript" language="javascript">
        $(document).ready(
                function () {
                    $('#listOfColleges').mouseover(function () {
                        $(this).css("color", "#b0c4de");
                    });

                    $('#listOfColleges').mouseout(function () {
                        $(this).css("color", "#4b4b4b");
                    });

                    $('#Create').click(function () {
                        var isError = false;
                        var errorString = '<html><body><ul>';

                        if ($('#name').val() == '') {
                            isError = true;
                            errorString += '<li>Please enter college name.</li>';
                        }
                        if ($('#import').val() == '') {
                            isError = true;
                            errorString += '<li>Please select a csv file.</li>';
                        }
                        errorString += "</ul></body></html>";
                        if (isError) {
                            $('#errorContainer').html(errorString);
                            return false;
                        }
                    });
                })

        function checkFile(sender) {
            var validExts = new Array(".csv");
            var fileExt = sender.value;
            fileExt = fileExt.substring(fileExt.lastIndexOf('.'));
            if (validExts.indexOf(fileExt) < 0) {
                alert("Invalid file selected, only" +
                        validExts.toString() + " files are accepted");
                sender.value = '';
                return false;
            }
            else return true;
        }
    </script>
<% end %>

<form action="/applicant/create" id="college" name="college" method="post" enctype="multipart/form-data">
  <div id="login-holder">
    <div id="logo-login">
      <div id="loginbox">
        <div id="login-inner">
          <div id="errorContainer" style="text-decoration-color: maroon; padding-bottom: 20px; color: maroon;">
            <%= @message %>
          </div>
          <p> College Name
            <input type="text" name="college_name" id="name" style="width: 100px; height: 15px;"></p>
          <br>
          <input id="import" type="file" name="file_name" onchange="checkFile(this)">
          <br/><br/><br/>

          <div style="text-align: center;">
            <input type="submit" id="Create" value="Create" style="float: left;">

            <a href="/applicant/home">
              <input type="button" value="Cancel" style="float: left; padding-top: 0px; "> </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>

app/views/college/show.html.erb
<% content_for :title do %>
    CampusHunter - List of Colleges
<% end %>


<% content_for :styles do %>
    <%= stylesheet_link_tag "pro_dropline_ie" %>
    <%= stylesheet_link_tag "pro_dropline" %>
<% end %>

<div id="page-heading">
  <h1>List of Colleges
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <%= params[:name] %>
    <div style="float: right;">
      <h2>
        <%= link_to "Add New College", new_college_path, :id => "addNewCollege", :style => "color: #4b4b4b;" %>
      </h2>
    </div>
  </h1>
</div>

<table border="0" width="100%" cellpadding="0" cellspacing="0" id="content-table">
  <tr>

    <th class="topleft"></th>
    <td id="tbl-border-top">&nbsp;</td>
    <th class="topright"></th>

  </tr>
  <tr>
    <td id="tbl-border-left"></td>
    <td>
      <div id="content-table-inner">
        <table id="college" border="0" width="100%" cellpadding="0" cellspacing="0">
          <tr>
            <th class="table-header-repeat line-left"><a>Name</a></th>
            <th class="table-header-repeat line-left"><a>Number Of Applicants</a></th>
            <th class="table-header-repeat line-left"><a>Cutoff</a></th>
            <th class="table-header-options line-left"><a>Options</a></th>
          </tr>

          <% @colleges.each do |college| %>
              <tr>
                <td><%= link_to college.name, url="/applicant/show/#{college.id}/#{college.name}" %></td>
                <td><%= college.number_of_applicants %></td>
                <td><%#= college.cutoff %></td>
                <td><%#= link_to "Delete", url="/college/delete/#{college.id }",
                                :confirm => "Are you sure you want to delete #{college.name}",:id => "remove" %></td>
              </tr>
          <% end %>
        </table>
      </div>
      <%# paginate @colleges %>
      <div class="clear"></div>
      </div>
    </td>
    <td id="tbl-border-right"></td>
  </tr>
  <tr>
    <th class="sized bottomleft"></th>
    <td id="tbl-border-bottom">&nbsp;</td>
    <th class="sized bottomright"></th>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CampusHunter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/session/new.html.erb
<%# content_for :title do %>
    <!--CampusHunter - Login-->
<%# end %>

<%#= form_tag(:url => '/session/create', :method => :post)  do %>
    <!--<div id="login-holder">-->
      <!--<div id="logo-login">-->
        <%#= image_tag "shared/logo.png", :size => "156*40",
                      :alt => "CampusHunter" %>
      <!--</div>-->
      <!--<div class="clear"></div>-->
      <!--<div id="loginbox">-->

        <!--<div id="login-inner">-->
          <!--<div class="red-left" style="padding-bottom: 10px;">-->
            <%#= @message %>
          <!--</div>-->
          <!--<table border="0" cellpadding="0">-->
            <!--<tr>-->
              <!--<th>Username</th>-->
              <!--<td>-->
                <%#= text_field_tag :username, params[:username], :class => "login-inp" %>
              <!--</td>-->
            <!--</tr>-->
            <!--<tr>-->
              <!--<th>Password</th>-->
              <!--<td>-->
                <%#= password_field_tag :password, params[:password], :class => "login-inp" %>
              <!--</td>-->
            <!--</tr>-->
            <!--<tr>-->
              <!--<th></th>-->
              <!--<td valign="top"><br/></td>-->
            <!--</tr>-->
            <!--<tr>-->
              <!--<th></th>-->
              <!--<td>-->
                <!--<button type="submit" class="submit-login">Login</button>-->
              <!--</td>-->
            <!--</tr>-->
          <!--</table>-->
        <!--</div>-->
      <!--</div>-->
    <!--</div>-->
<%# end %>

<h1>CampusHunter - Login</h1>
<%= form_tag(:url => '/session/create', :method => :post)  do %>
    <div>
    <%= @message %>
    </div>
    <div>
    <label>Username</label>
      <span>
    <%= text_field_tag :username, params[:username]%>
          </span>
    </div>
    <div>
      <label>Password</label>
      <span>
    <%= password_field_tag :password, params[:password]%>
          </span>
    </div>
    <button type="submit">Login</button>
<% end %>

app/views/user/destroy.html.erb
<% content_for :title do %>
    CampusHunter - Delete User
<% end %>

<% content_for :scripts do %>
    <script type="text/javascript">

        $(Document).ready(function () {
            $('#Delete').click(function () {
                if ($('.login-inp').val() == '') {
                    $('#errorContainer').text('Please enter username.');
                    return false;
                }
            });
        });
    </script>
<% end %>

<form action="/users/del" id="users" name="users" method="post" enctype="multipart/form-data">
  <div id="login-holder">
    <div id="logo-login">
      <img style="width: 156px; height: 40px;" src="/assets/shared/logo.png" alt="Logo"/>
    </div>
    <div class="clear"></div>
    <div id="loginbox">
      <div id="login-inner">
        <table style="width: 100%;">
          <tr>
            <td colspan="3">
              <div id="errorContainer" style="text-decoration-color: maroon; padding-bottom: 20px; color: maroon;">
                <%= @message %>
              </div>
            </td>
          </tr>
          <tr>
            <td>
              <label for="username">Username</label>
            </td>
            <td></td>
            <td>
              <input type="text" name="username" id="username" class="login-inp" >
            </td>
          </tr>
          <tr>
            <td colspan="3"><br/><br/></td>

          </tr>
          <tr style="text-align: center;">
            <td colspan="3" style="text-align: center;">
              <input type="submit" id="Delete" class="submit-login" value="Delete" style="float: left;">
              &nbsp; &nbsp; &nbsp;
              <a href="/college/show">
                <input type="button" value="Cancel" class="submit-login" style="float: left; padding-top: 0px; ">
              </a>
            </td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</form>

app/views/user/new.html.erb
<% content_for :title do %>
    CampusHunter - Add New User
<% end %>


<% content_for :scripts do %>
    <script type="text/javascript">

        function changeId() {
            $('#loginbox').attr('id', 'signup');
        }
    </script>
<% end %>


<%= form_for :user, :url => {:action => :create} do |f| %>
    <div id="login-holder">
      <div id="logo-login">
        <img style="width: 156px; height: 40px;" src="/assets/shared/logo.png" alt="Logo"/>
      </div>
      <div class="clear"></div>
      <div id="loginbox">
        <div id="login-inner" style="width: 400px;">
          <table border="0" cellpadding="0">
            <tr>
              <td colspan="2">
                <div id="message-red">
                  <div id="errorContainer" style="text-decoration-color: maroon; color: maroon;">
                    <%= @message %>
                  </div>
                  <% if @user.errors.any? %>
                      <%= javascript_tag "changeId();" %>
                      <table border="0" width="100%" cellpadding="0" cellspacing="0">
                        <tr>
                          <td class="red-left">
                            <ul>
                              <% @user.errors.full_messages.each do |message| %>
                                  <li><%= message %></li>
                              <% end %>
                            </ul>
                          </td>
                        </tr>
                      </table>
                  <% end %>
                </div>
              </td>
            </tr>
            <tr>
              <th><%= f.label :username %></th>
              <td>
                <%= f.text_field :username, :class => "login-inp" %>
              </td>
            </tr>
            <tr>
              <th><%= f.label :password %></th>
              <td>
                <%= f.password_field :password, :class => "login-inp" %>
              </td>
            </tr>
            <tr>
              <th style="width: 160px;"> <%= f.label "Re-enter Password" %></th>
              <td>
                <%= f.password_field :password_confirmation, :class => "login-inp" %>

              </td>
            </tr>
            <tr>
              <th></th>
              <td valign="top"><br/></td>
            </tr>
            <tr>
              <th></th>
              <td>
                <%= f.submit "Add", :label => 'Add', :class => "submit-login" %>
                &nbsp;&nbsp;&nbsp;
                <a href="/college/show">
                  <input type="button" value="Cancel" class="submit-login" style="padding-top: 0px; ">
                </a>
              </td>
            </tr>
          </table>
        </div>
      </div>
    </div>
<% end %>